typography_spectrum: 0.3642
color:
  brandColors:
    - '#ffffff'
    - '#7ca9dc'
    - '#5e5e5e'
    - '#bad3ef'
    - '#5278a5'
  brandStrength: 1
  lightness: 0.3028031613212079
  saturation: 0
  rhythmicContrast: 0.35476266127079725
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: Blue Jay Technology
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Blue Jay Technology - The Digital Marketing Company
description: Where digital meets magic
purpose: []
